backend:
  name: git-gateway
  branch: main

media_folder: "src/public/blog_media"

collections:
  - name: "blog" 
    label: "Blog" 
    folder: "src/data/posts" 
    create: true
    extension: "json"
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}" 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Category", name: "category", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Language", name: "language", default: "en", widget: "hidden"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      # - {label: "Featured Image", name: "thumbnail", widget: "image"}